allow-branch = ["main"]
publish = true
pre-release-commit-message = "Bump version to {{version}}"
shared-version = true
consolidate-commits = true
tag-message = "{{tag_name}}"
tag-name = "{{version}}"
